### ISSUE TITLE
Fabric error - Incorrect JDK

### ISSUE THREAD

**Issue by Tech-How** [Gaming32/additive-installer#4]
Hi, I noticed that when using this installer for the latest game version (1.20.6 at the time of writing), the game launches with a Fabric modloader error. This can be solved by downloading JDK 21 from Oracle's website and manually pointing the Minecraft install to it. Is this something that can be automated by this installer? I was confused at first and it took me some time to figure out what went wrong. Bundling the JDK in the .minecraft folder or under the launcher install runtime folder would probably be best instead of installing it.

Also, thanks for making this! Kinda shocked it only has 3 watchers and 6 stars.

**Comment by Gaming32** [comment]
This is because of a hack workaround I did where MC 1.17 and older of the pack wouldn't work in environments older than Java 17, so I hardcoded it to 17. This hasn't been an issue in a while, so this workaround should be removed.
